############################ FACTURAS ############################

### GET FACTURAS
GET http://localhost:3002/api/facturas

### GET FACTURA
GET http://localhost:3002/facturas/1/detalles

### NUEVA FACTURA
POST http://localhost:3002/facturas
Content-Type: application/json

{
    "origen": "Proveedor Z",
    "pedido_pos": 199,   
    "obra": "Obra 1",
    "fecha": "2025-09-05",
    "concepto_f": "",
    "concepto_l": "",
    "cobrado": 0,
    "importe": 500,
    "obs_imp": "",
    "importe_base": 500,     
    "iva": 14,               
    "factura_num": "FAC001"
}


### PUT

PUT http://localhost:3002/facturas/15
Content-Type: application/json

{
    "cobrado": 1,
    "importe": 500,
    "obs_imp": "Pagado",
    "importe_base": 500,     
    "iva": 14               
}

### DELETE FACTURA

DELETE http://localhost:3002/facturas/15

############################ OBRAS ############################

### GET Obras
GET http://localhost:3002/api/obra

### GET Obra específica
GET http://localhost:3002/api/obra/4147

### POST Obra
POST http://localhost:3002/api/obra
Content-Type: application/json

{
    "cod": "000A",
    "desc": "Instalación de alarma",
    "fechaSeg": "2025-04-04",
    "tipoObra": 3,
    "facturable": 1,
    "estadoObra": 4,
    "fechaAlta": "2025-04-04",
    "usuarioAlta": 4,
    "fechaFin": "2025-06-04",
    "fechaOferta": "2025-04-04",
    "horasPrevistas": 30,
    "gastoPrevisto": 200,
    "importe": 100,
    "viabilidad": 100,
    "empresa": 2,
    "contacto": 3,
    "edificio": 39,
    "observaciones": "Esta es una obra creada de prueba",
    "observacionesInternas": "Esta es una obra creada de prueba"
}

### Actualizar obra
PUT http://localhost:3002/api/obra/5302
Content-Type: application/json

{
    "cod": "000A",
    "desc": "Instalación de alarma",
    "fechaSeg": "2025-04-04",
    "tipoObra": 3,
    "facturable": 1,
    "estadoObra": 4,
    "fechaAlta": "2025-04-04",
    "usuarioAlta": 4,
    "fechaFin": "2025-06-04",
    "fechaOferta": "2025-04-04",
    "horasPrevistas": 30,
    "gastoPrevisto": 200,
    "importe": 100,
    "viabilidad": 100,
    "empresa": 2,
    "contacto": 3,
    "edificio": 39,
    "observaciones": "Esto es una obra actualizada de prueba",
    "observacionesInternas": "Esto es una obra actualizada de prueba"
}

### Eliminar obra
DELETE http://localhost:3002/api/obra/5302
Content-Type: application/json

{
    "codigoUsuarioBaja": 4
}

### ENDPOINTS PARA LOS FORMS

### TIPOS DE OBRA
GET http://localhost:3002/api/tipos-obra


###### ENDPOINTS ALMACEN #############

### Obtener todos los productos
GET http://localhost:3002/api/almacen

### Obtener un producto específico
GET http://localhost:3002/api/almacen/244

### Crear un producto
POST http://localhost:3002/api/almacen
Content-Type: application/json

{
  "cod": "123456",
  "descripcion": "Material de prueba",
  "etiqueta": "uds.",
  "proveedor": 850,
  "familia": 2,
  "tipoUnidad": 3,
  "fechaAlta": "2016-06-21",
  "usuarioAlta": 4,
  "stock": 20,
  "stockMin": 3,
  "stockMax": 1000,
  "marca": 1,
  "precioUnitario": 1,
  "precioTotal": 4,
  "observaciones": "Material de prueba"
}

### Actualizar un producto
PUT http://localhost:3002/api/almacen/244
Content-Type: application/json

{
  "cod": "123456",
  "descripcion": "Material de prueba",
  "etiqueta": "uds.",
  "proveedor": 850,
  "familia": 2,
  "tipoUnidad": 3,
  "fechaAlta": "2016-06-21",
  "usuarioAlta": 4,
  "stock": 20,
  "stockMin": 3,
  "stockMax": 1000,
  "marca": 1,
  "precioUnitario": 1,
  "precioTotal": 4,
  "observaciones": "Observaciones actualizadas"
}

### Borrar un producto
DELETE http://localhost:3002/api/almacen/244
Content-Type: application/json

{
    "codigoUsuarioBaja": 14
}

###### ENDPOINTS CONTACTO #############

### Obtener contacto por id de empresa
GET http://localhost:3002/api/contacto/2

###### ENDPOINTS EDIFICIO #############

### Obtener edificios
GET http://localhost:3002/api/edificio

###### ENDPOINTS EMPRESA #############

### Obtener empresas
GET http://localhost:3002/api/empresa

###### ENDPOINTS ESTADO OBRA #############

### Obtener estados obra
GET http://localhost:3002/api/estado-obra

###### ENDPOINTS TIPO FACTURABLE #############

### Obtener tipos facturable
GET http://localhost:3002/api/tipo-facturable

###### ENDPOINTS TIPO OBRA #############

### Obtener tipos obra
GET http://localhost:3002/api/tipo-obra

###### ENDPOINTS USUARIO #############

### Obtener usuarios
GET http://localhost:3002/api/usuario

###### ENDPOINTS RELACION - OBRAS #############

### Obtener padre de una obra
GET http://localhost:3002/api/relacion-obras/padre/2

### Obtener hijas de una obra
GET http://localhost:3002/api/relacion-obras/hijas/1

### Establecer un padre a una obra
POST http://localhost:3002/api/relacion-obras/padre
Content-Type: application/json

{
    "idObraPadre": null,
    "idObraHija":2
}

### Establecer hijas a una obra
POST http://localhost:3002/api/relacion-obras/hijas
Content-Type: application/json

{
    "idObraPadre" : 1,
    "idsObrasHijas" : []
}

###### ENDPOINTS RENTABILIDAD #############

### Obtener rentabilidad
GET http://localhost:3002/api/rentabilidad/4536

###### ENDPOINTS ECOPEDIDOS #############

### Obtener pedidos asociados a una obra
GET http://localhost:3002/api/ecoPedido/62

###### ENDPOINTS ECOFACTURAS #############

### Obtener facturas asociadas a una obra
GET http://localhost:3002/api/ecoFactura/62

###### ENDPOINTS GASTOS #############

### Obtener todos los gastos por validar
GET http://localhost:3002/api/gastos/por-validar

### Obtener todos los gastos por pagar
GET http://localhost:3002/api/gastos/por-pagar

### Obtener todos los gastos de una obra
GET http://localhost:3002/api/gastos/obra/4536

