export const facturas = [
    { 
      origen: 'DQEMS', 
      facturaPos: 'F001', 
      pedidoPos: 'P1001', 
      obra: '3801R0', 
      fecha: '2023-01-15', 
      conceptoF: 'Mantenimiento preventivo maquinaria', 
      conceptoL: 'Reparación de piezas y ajustes', 
      cobrado: 'Sí', 
      fechaCobrado: '2023-02-10', 
      importe: 1500.50, 
      obsFImport: 'Import'
    },
    { 
      origen: 'GESTOR', 
      facturaPos: 'F002', 
      pedidoPos: 'P1002', 
      obra: '4319R0', 
      fecha: '2024-03-05', 
      conceptoF: 'Instalación equipos eléctricos', 
      conceptoL: 'Montaje y ajuste de sistemas eléctricos', 
      cobrado: 'No', 
      fechaCobrado: '[no]', 
      importe: 2200.75, 
      obsFImport: 'No import'
    },
    { 
      origen: 'DQEMS', 
      facturaPos: 'F003', 
      pedidoPos: 'P1003', 
      obra: '1234R5', 
      fecha: '2023-07-18', 
      conceptoF: 'Suministro y colocación de material', 
      conceptoL: 'Compra de materiales para la obra', 
      cobrado: 'Sí', 
      fechaCobrado: '2023-08-01', 
      importe: 1200.00, 
      obsFImport: 'Import'
    },
    { 
      origen: 'GESTOR', 
      facturaPos: 'F004', 
      pedidoPos: 'P1004', 
      obra: '2345R6', 
      fecha: '2023-10-12', 
      conceptoF: 'Servicios de limpieza industrial', 
      conceptoL: 'Limpieza de maquinaria y equipos', 
      cobrado: 'No', 
      fechaCobrado: '[no]', 
      importe: 800.00, 
      obsFImport: 'No import'
    },
    { 
      origen: 'DQEMS', 
      facturaPos: 'F005', 
      pedidoPos: 'P1005', 
      obra: '3456R7', 
      fecha: '2023-09-07', 
      conceptoF: 'Reparación de maquinaria pesada', 
      conceptoL: 'Reparación y mantenimiento de equipos grandes', 
      cobrado: 'Sí', 
      fechaCobrado: '2023-10-15', 
      importe: 3500.40, 
      obsFImport: 'Import'
    },
    { 
      origen: 'GESTOR', 
      facturaPos: 'F006', 
      pedidoPos: 'P1006', 
      obra: '9876R5', 
      fecha: '2023-11-20', 
      conceptoF: 'Desmontaje y traslado de equipos', 
      conceptoL: 'Trabajo de desmontaje de maquinaria y traslado a nuevo local', 
      cobrado: 'No', 
      fechaCobrado: '[no]', 
      importe: 1500.00, 
      obsFImport: 'No import'
    },
    { 
      origen: 'DQEMS', 
      facturaPos: 'F007', 
      pedidoPos: 'P1007', 
      obra: '6789R1', 
      fecha: '2023-08-25', 
      conceptoF: 'Reemplazo de piezas defectuosas', 
      conceptoL: 'Sustitución de piezas rotas y revisión de equipo', 
      cobrado: 'Sí', 
      fechaCobrado: '2023-09-12', 
      importe: 500.00, 
      obsFImport: 'Import'
    },
    { 
      origen: 'GESTOR', 
      facturaPos: 'F008', 
      pedidoPos: 'P1008', 
      obra: '7890R2', 
      fecha: '2023-06-05', 
      conceptoF: 'Instalación de sistemas de aire acondicionado', 
      conceptoL: 'Instalación de nuevas unidades de climatización', 
      cobrado: 'No', 
      fechaCobrado: '[no]', 
      importe: 2800.20, 
      obsFImport: 'No import'
    },
    { 
      origen: 'DQEMS', 
      facturaPos: 'F009', 
      pedidoPos: 'P1009', 
      obra: '8901R3', 
      fecha: '2023-04-10', 
      conceptoF: 'Revisión y calibración de sistemas', 
      conceptoL: 'Revisión de todos los sistemas de control', 
      cobrado: 'Sí', 
      fechaCobrado: '2023-05-01', 
      importe: 1300.30, 
      obsFImport: 'Import'
    },
    { 
      origen: 'GESTOR', 
      facturaPos: 'F010', 
      pedidoPos: 'P1010', 
      obra: '9012R4', 
      fecha: '2023-03-15', 
      conceptoF: 'Mantenimiento de maquinaria pesada', 
      conceptoL: 'Mantenimiento preventivo y correctivo', 
      cobrado: 'No', 
      fechaCobrado: '[no]', 
      importe: 1700.75, 
      obsFImport: 'No import'
    }
  ];