### Obtener todas las compras
GET http://localhost:3002/compras
Accept: application/json

###

### Obtener una compra por número
GET http://localhost:3002/compras/F0069
Accept: application/json

###

### Crear una nueva compra
POST http://localhost:3002/compras
Content-Type: application/json

{
  "numero": "F0069",
  "fechaFactura": "2025-09-12",
  "concepto": "Compra de material",
  "proveedor": "Proveedor XYZ",
  "tipo": "Factura",
  "baseIva": 100.50,
  "totalIva": 21.10,
  "asignado": true,
  "totalAsignado": 50,
  "observaciones": "Observaciones de prueba"
}

###

### Actualizar completamente una compra (PUT)
PUT http://localhost:3002/compras/F0069
Content-Type: application/json

{
  "numero": "F0069",
  "fechaFactura": "2025-09-13",
  "concepto": "Compra actualizada",
  "proveedor": "Proveedor ABC",
  "tipo": "Factura",
  "baseIva": 200.00,
  "totalIva": 42.00,
  "asignado": false,
  "totalAsignado": 100,
  "observaciones": "Actualización completa"
}

###

### Actualización parcial de una compra (PATCH)
PATCH http://localhost:3002/compras/F001
Content-Type: application/json

{
  "concepto": "Cambio parcial",
  "totalIva": 50.00
}

###

### Eliminar una compra
DELETE http://localhost:3002/compras/F0069
Accept: application/json